name: Release

on:
  push:
    tags:
      - "0.0.1"

  workflow_dispatch:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  test_apple_platforms:
    name: Test on iOS
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - "platform=iOS Simulator,name=iPhone 15"

    steps:
      - uses: actions/checkout@v4
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme sdk-ios-playground -destination "${{ matrix.destination }}" | xcbeautify

  test_spm:
    name: Test SPM
    build:
    #specify OS to run the jobs on
    runs-on: macos-latest
    #sequential steps to run for the `build` job
    steps:
      # step 1, use Marketplace action called Checkout@v2, to checkout the code
    - uses: actions/checkout@v4 #'uses' keyword launches the Marketplace action
      # step 2, verbosely build the package using the `swift` CLI
    - name: Build
      run: swift build -v #'run' keyword executes the command, as if it's run in terminal
      # step 3, verbosely test the package using the `swift` CLI
    - name: Run tests
      run: swift test -v

  release:
    needs: [test_apple_platforms, test_spm]
    name: Create a new GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: woke
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          token: ${{ secrets.TOKEN_GB }}
